app/controllers/application_controller.rb, db/migrate/20220221131933_add_first_name_and_last_name_to_users.rb, db/schema.rb
J'ai ajouté les first et last name au model User
=> info user ok

app/models/user.rb, app/views/devise/registrations/new.html.erb, db/schema.rb
J'ai ajouté ces infos dans le formulaire Sign up, et validations
=> first et last name ok

app/controllers/motos_controller.rb, app/views/motos/index.html.erb, app/views/motos/show.html.erb
J'ai mis a jour le New le show le index et le create de Moto
=> show/New/Index Moto done

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, db/schema.rb
=> Creation-footer

app/assets/stylesheets/components/_card.scss, app/views/motos/index.html.erb
Pas grand chose de modif mais juste un ajout de navbar, une tentative de "card" a la airBnb mais sans succès...
je dois traavailler mon CSS :)
=> modif index

app/controllers/motos_controller.rb, app/views/motos/show.html.erb
=> destroy method moto done

app/controllers/motos_controller.rb, app/views/motos/index.html.erb
=> ok bouton home

app/assets/stylesheets/components/_card.scss, app/views/dashboards/profile.html.erb, app/views/motos/index.html.erb
Yo, j'ai commencé le layout de cette page.
=> profile page V1

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/views/dashboards/profile.html.erb
j'ai ajouté des choses sympathiques
=> ok profile

app/assets/stylesheets/components/_card.scss, app/views/dashboards/profile.html.erb
=> dashboard css

app/assets/stylesheets/components/_footer.scss, app/views/layouts/application.html.erb, app/views/motos/index.html.erb
=> Footer fixed on all pages and modif

app/views/motos/edit.html.erb
J'ai ajouté le champ adresse en mode geocod
=> address ok dans edit

app/assets/stylesheets/components/_footer.scss, app/views/layouts/application.html.erb
=> Forum added on footer

Gemfile, Gemfile.lock
J'ai juste ajouter la GEM, rien de plus. Un bundle install juste pr l'avoir sur vos versions mais pas encore effective
=> ok gem pundit

app/assets/stylesheets/components/_avatar.scss
=> Avatar fixed

app/assets/stylesheets/components/_map.scss, app/controllers/motos_controller.rb, app/javascript/controllers/mapbox_controller.js, app/views/motos/_infos_window.html.erb
Le style laisse à desirer... si qq un veut y jetter un oeil... FEEL FREE
=> ok pop up mais sans le style CSS

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/views/dashboards/profile.html.erb, app/views/motos/show.html.erb, app/views/shared/_navbar.html.erb
=> avatar active works properly now

app/assets/stylesheets/components/_card.scss, app/views/dashboards/profile.html.erb
=> patch dashboard scss

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_checkbox.scss, app/controllers/bookings_controller.rb, app/views/dashboards/profile.html.erb
=> Loop is done

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_checkbox.scss, app/views/dashboards/profile.html.erb
first name and last name align
=> form first name and last name align
